### PR TITLE
[flux-core v0.13] example8: Update README, add fetch-stdout.sh and remove outdated scripts

### PR DESCRIPTION
**Pull request by cmoussa1**
This PR makes the following changes:

1. **README.md**
- Update styling format for instructions from bullet points to numbered instructions
2. **fetch-stdout.sh**
- Instead of using a Python/Lua script to display the KZ interface, we introduce a shell script to display the same functionality; as a result, I remove both the Python and Lua scripts because they are no longer used/outdated. Once the Python API changes have been merged into `master`, I'd be happy to recreate the Python script and include it in this directory.

### CODE REVIEW

**Comment by dongahn** [comment]
@cmoussa1: Thanks. I think the IO subsystem is no longer called KZ. @grondo or @chu11: what should we refer the IO stream subsystem within flux to as?

**Comment by dongahn** [comment]
@grondo or @trws: if users want to fetch IO stream within Python, what interface is suggested at this time?

**Comment by trws** [comment]
I don't know with the new system, it would have been KZ before as you mentioned but I don't know the new setup yet.

**Comment by grondo** [comment]
Currently output is written to an eventlog in the KVS under `guest.output`.

The format of this eventlog is documented as [Flux Job Standard I/O V1](https://github.com/flux-framework/rfc/blob/master/spec_24.adoc)

There really isn't a nice C or Python interface for eventlogs (and thus not the job stdio), and readers need to first synchronize on the `guest.exec.eventlog`, which in turn requires synchronization on the main job `eventlog`. (see `flux job attach` for example)

We have some work to do here to match usability of the old system.

**Comment by dongahn** [comment]
Maybe we should exclude this example for the new execution system for awhile then?

**Comment by grondo** [comment]
Yeah, since we don't have something like "KZ streams" we should rework the example. A simple first cut could be something like

## Job output handling

### Dumping output for completed jobs

```console
$ flux mini submit hostname
150994944000
$ flux job wait-event 150994944000 clean
1575599774.703037 clean
$ flux job attach  150994944000
fluke108
$ 
```

**Comment by grondo** [comment]
We could extend the above with some examples of "Redirecting output to a file" and show that `flux job attach` prints the redirect events to the users' console.

Later, when we have a programmatic interface, we could add examples of reading the IO eventlogs from Python.

**Comment by cmoussa1** [comment]
I will close this pull request since we are dropping this example for now.

**Pull request closed without merging**
