### PR TITLE
[WIP][flux-core v0.13] Add top level README

### PR DESCRIPTION
**Pull request by cmoussa1**
This PR adds a top level README with links to each example and a short description of the example.

Since we are considering a rework of [example8](https://github.com/flux-framework/flux-workflow-examples/tree/master/example8), I included a note below the description:

_Note: This example is in the process of being reworked to show different functionality within Flux._

I'm not sure if this is the best wording we want in the README, or if we even want to keep example8 in the repo in the first place; that is the reason for the **[WIP]** tag.

### CODE REVIEW

**Comment by grondo** [comment]
> I'm not sure if this is the best wording we want in the README, or if we even want to keep example8 in the repo in the first place; that is the reason for the [WIP] tag.

I would just remove example 8 for now.

**Comment by cmoussa1** [comment]
Thanks for your feedback @grondo! I went ahead and just removed the example8 directory, as well as renamed examples9 and 10 down to 8 and 9, respectively. I'll go ahead and drop the **[WIP]** tag as well.

**Comment by cmoussa1** [comment]
Actually, now that I think about it, maybe I should hold off on this PR until the data conduit example (originally `example10`) is accepted and merged into `master`? Since this PR removes `example8` and renames the data conduit example to `example9`.

**Comment by dongahn** [comment]
> Actually, now that I think about it, maybe I should hold off on this PR until the data conduit example (originally example10) is accepted and merged into master? Since this PR removes example8 and renames the data conduit example to example9.

Sounds good to me.

**Comment by cmoussa1** [comment]
had to pull some changes from `master` and merge them with this branch to fix some conflicts since this removed **example8** and renamed the last two directories.

**Comment by cmoussa1** [comment]
@dongahn Since I merged this branch with updated `master`, trying to `rebase` shows all of the commits from the merge as well. Is there a certain strategy to work around this so I can squash the first three commits from this branch before the merge?

**Comment by grondo** [comment]
>  Since I merged this branch with updated master, trying to rebase shows all of the commits from the merge as well. Is there a certain strategy to work around this so I can squash the first three commits from this branch before the merge?

The workflow is to always rebase onto master, not merge master into your branch.

You can revert to where you were before your merge (you might find `git reflog` useful here), then do a rebase of your branch on top of master `git rebase origin/master`. If there are conflicts, the rebase will stop so you can resolve the conflicts.

**Comment by dongahn** [comment]
Thanks @grondo!

**Comment by cmoussa1** [comment]
Thanks @grondo! That corrected the issue I was running into. I think to make the changes even clearer I'll separate the two major changes proposed in this PR 

1. removing **example8** and renaming **example9** and **example10**
2. adding a top-level README

into two small PR's.

**Comment by dongahn** [comment]
Sounds good to me @cmoussa1.

**Pull request closed without merging**
