### PR TITLE
example3 doc: Update README.md to match new execution system commands

### PR DESCRIPTION
**Pull request by cmoussa1**
This PR makes the following changes to `example3/README.md`:

- Add numbered steps instead of bullet points for command line instructions
- Add bash/zsh syntax for setting `FLUX_SCHED_OPTIONS`
- Remove LC Path for Flux executable
- Change format of command line instructions from **bold** font to `in-line code`
- Add example output after `flux mini submit`

### CODE REVIEW

**Comment by cmoussa1** [comment]
I need to fix this README as well and remove the `FLUX_SCHED_OPTIONS` instructions from the walkthrough.

**Comment by cmoussa1** [comment]
OK, force-pushed the update to remove `FLUX_SCHED_OPTIONS` instruction from the walkthrough; I believe this is ready for review now!

**Comment by dongahn** [comment]
Perfect. Thanks!

**Comment by cmoussa1** [comment]
Thank you!

**Pull request merged**
