### PR TITLE
doc: Update README.md and example scripts in example6/

### PR DESCRIPTION
**Pull request by cmoussa1**
This PR introduces the following changes to three files in this repository:

**README.md**
Changed format of instructions on example code; set example instructions for unsetting environment variable `FLUX_SCHED_OPTIONS` in both tcsh and bash/zsh shells.

**parent.sh**
Changed `NCORES` in from 216 to 3, and removed `-s1` flag from `flux submit` command.

**ensemble.sh**
Changed `NJOBS` from 5000 to 750.

### CODE REVIEW

**Comment by dongahn** [comment]
@cmoussa1: This looks good. However, could you add some notes in the README.md as to how once can increase the number of jobs by increasing `NCORES` and `NJOBS` knobs? 

The readme says this example is about "very large ensemble" but the currently used parameters are not large enough. So you may want to say, for those who want to experiment with larger ensembles, here is what you can do...

**Comment by cmoussa1** [comment]
> @cmoussa1: This looks good. However, could you add some notes in the README.md as to how once can increase the number of jobs by increasing `NCORES` and `NJOBS` knobs?

Yes, good suggestion. Will add that now.

**Comment by dongahn** [comment]
Thanks. Merging.

**Comment by cmoussa1** [comment]
Thank you!

**Pull request merged**
