### PR TITLE
Add examples for kz interfaces and kvs interfaces

### PR DESCRIPTION
**Pull request by dongahn**
@koning: This PR has some examples to show how one can use kz stream (using either python or lua binding) to fetch stdout of a job.

### CODE REVIEW

**Comment by dongahn** [comment]
@koning: I also added kvs interface examples. https://github.com/flux-framework/flux-workflow-examples/pull/4/commits/12479230d13c286584a2ebf3d927fb25c5d2176c

**Comment by dongahn** [comment]
@koning:

 If you needs an atomic operation, you will need to use a slightly different `job.submit` sequence where you get the jobid first and then submit your request. Then, you can install jsc, kz and other handlers which can do better when the installation happens before the actual submission. If you are interested in this, I can add an example.

That said, I think you can create and do kz attach while the job is running too. But remember that, the StringIO buffer will filled up when the kz callback handler is called to fetch the stdout. So the full content will be available after you return from the reactor. 

```
f = flux.Flux ()
resp = f.rpc_send ("job.submit", payload)
if resp is None:
    print "flux.rpc: compute_jobreq", "failed"

jobid = resp['jobid']
jobid_req = {
    "ids" : [jobid]
}
payload = json.dumps (jobid_req)

resp = f.rpc_send ("job.kvspath", payload)
if resp is None:
    print "flux.rpc: job.kvspath", "failed"

rootstdout = StringIO.StringIO()
kz.attach (f, resp['paths'][0]  + ".0.stdout", rootstdout)

f.reactor_run (f.get_reactor (), 0)
print rootstdout.getvalue ()
```

**Comment by SteVwonder** [comment]
@dongahn: what you have so far in this PR LGTM.  Do you want me to merge now and if you decide to add the atomic example, you can submit another PR? Or do you want to roll the atomic example into this PR?

**Comment by dongahn** [comment]
@StevWonder: I won't be able other examples anytime soon due to travel. Please merge. Thanks in advance!

**Pull request merged**
