### PR TITLE
Add example7 to show JSC and reactor howtos

### PR DESCRIPTION
**Pull request by dongahn**
Per a user's request.

Common use case where a workflow manager wants to keep track of the lifecycle of a group of jobs and react to certain events such as completion and failure.

### CODE REVIEW

**Comment by dongahn** [comment]
FYI -- I wasn't able to get this example to work with Python `threading`. `rpc.send` or `reactor` was randomly failing with `errno=EINVALD`. I suspect there are some race conditions... It will be good to figure out exactly what is wrong with that approach at some point. 

Also @trws, is there a way to export C job state enumerator from the JSC python wrapper?   

https://github.com/dongahn/flux-workflow-examples/blob/179ae08fe7a748a2aaacea04d716f7fae0b818a5/example7/bookkeeper.py#L49

Still using the "named state" which might not translate when there are churns in execution system.

**Comment by trws** [comment]
Yeah, none of that stuff is thread-safe, and I don’t mean just in the python bindings either.  You can use multiprocess to get a similar effect though, capacitor does it that way.

We can have the bindings export anything.  In fact, if it’s an enumeration it’s probably already exported just not explicitly named, or maybe not in the public API.  Anything like that gets picked up at build time and added.

As to the TypeError, I need a full stack trace to figure that one out.  It looks like it’s happening during cleanup somehow, which makes me think something is getting cleaned up out of order.  Maybe something going funny with cleaning up the callback handles or something.

**Comment by dongahn** [comment]
> As to the TypeError, I need a full stack trace to figure that one out. It looks like it’s happening during cleanup somehow, which makes me think something is getting cleaned up out of order. Maybe something going funny with cleaning up the callback handles or something.

Sounds likely. You can easily repro this with the example in this PR.

**Comment by dongahn** [comment]
@SteVwonder: I think this can land as is for now.

**Pull request merged**
